name: schedule

on:
  schedule:
    - cron: "00 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: run node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - run: npm install

      - name: code
        run: |
          git config --local user.email "2071916845@qq.com"
          git config --local user.name "it985"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.shaoshupai-trending-hot-search }}@github.com/${{ github.repository }}
          git pull origin master
          node mod.js
          git add .
          git commit -m "update shaoshupai-trending-hot-search"
          git push origin master
